### ISSUE TITLE
Initialization of weights and normalization

### ISSUE THREAD

**Issue by mparaschiv** [adeshpande3/Tensorflow-Programs-and-Tutorials#2]
Hi, Nice implementation, however I see you are not doing two important things underlined in the paper:

1) Weight initialization to sqrt(1/in_dim) so not the default Xavier init. 
2) Normalization of the input (mean 0 , stddev 1) . 

This probably explains the poor results you got with the CNN.

**Comment by adeshpande3** [comment]
Thanks for bringing this up. Are you referring to the GAN tutorial, or the CNN one?

Regardless, I didn't include those mainly because I just wanted to keep this a very simple tutorial and aimed for mainly teaching (and not performance) purposes. 

But you're right, it definitely does have an impact on accuracy, so I'll add that in for people to include if they'd like, or you could go ahead and submit a pull request :).
